apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-ui-deployment
  labels:
    app: expense-tracker
    tier: frontend
spec:
  # Load Balancing: Kubernetes will ensure 2 replicas (Pods) of the UI are running.
  replicas: 2
  selector:
    matchLabels:
      app: expense-tracker
      tier: frontend
  template:
    metadata:
      labels:
        app: expense-tracker
        tier: frontend
    spec:
      containers:
      - name: client
        # *** MUST USE THE FIXED :v12 IMAGE ***
        image: vaibhavik26/expense-tracker-ui:v17
        ports:
        - containerPort: 80 # The Nginx container in the Dockerfile exposes port 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui-service # Internal name used by the Ingress
spec:
  selector:
    app: expense-tracker
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # Target container port
  type: ClusterIP # Only accessible from inside the cluster
