apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-server-deployment
  labels:
    app: expense-tracker
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
      component: server
  template:
    metadata:
      labels:
        app: expense-tracker
        component: server
    spec:
      containers:
      - name: expense-tracker-server
        image: expense-tracker:v1
        imagePullPolicy: Never 
        ports:
        - containerPort: 5000
        # --- Inject environment variables from the Secret ---
        envFrom:
        - secretRef:
            name: mongo-uri-secret # References the secret created in Step 1
